routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/meetings_clear', 'AdminController@users_meetings_clear')->name('users.meetings_clear');


        // settings

        Route::get('/admin-control', 'AdminController@admin_control')->name('control');

        Route::get('/ios-control', 'AdminController@ios_control')->name('ios-control'); 

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        Route::get('/subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        // Route::get('/subscription/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

        Route::get('/subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('/subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('/subscriptions/create', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('/subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('/subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('/subscriptions/status', 'AdminController@subscriptions_status_change')->name('subscriptions.status');

        Route::get('/subscriptions/popular/status', 'AdminController@subscriptions_popular_status')->name('subscriptions.popular.status');

        Route::get('/subscriptions/users', 'AdminController@subscriptions_users')->name('subscriptions.users');

        Route::get('subscriptions/payments' , 'AdminController@subscription_payments')->name('subscription.payments');

        Route::get('meetings' , 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');
       
        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');
        
        Route::get('meetings/end', 'AdminController@meetings_end')->name('meetings.end');

        //User Subscriptions

        Route::get('/users/subscriptions/', 'AdminController@users_subscriptions_index')->name('users.subscriptions');

        Route::get('/users/subscriptions/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

        Route::get('/users/subscriptions/view' , 'AdminController@user_subscriptions_view')->name('users.subscriptions.view');


    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');

app/Subscription.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Subscription extends Model
{

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'description', 'plan', 'amount', 'no_of_users', 'no_of_hrs'];

    protected $appends = ['plan_text', 'subscription_amount_formatted', 'no_of_users_formatted', 'no_of_hrs_formatted', 'currency', 'subscription_id'];

    public function getSubscriptionIdAttribute() {

        return $this->id;
    }

    public function getPlanTextAttribute() {

        return formatted_plan($this->plan);
    }

    public function getSubscriptionAmountFormattedAttribute() {

        return formatted_amount($this->amount);
    }

    public function getNoOfUsersFormattedAttribute() {

        return no_of_users_formatted($this->no_of_users);
    }

    public function getNoOfHrsFormattedAttribute() {

        return no_of_hrs_formatted($this->no_of_hrs, $this->no_of_hrs_type);
    }

    public function getCurrencyAttribute() {

        return \Setting::get('currency' , '$');
    }

    /**
	 * Save the unique ID 
	 *
	 *
	 */
    public function setUniqueIdAttribute($value){

		$this->attributes['unique_id'] = uniqid(str_replace(' ', '-', $value));
	}

    /**
     * Get the UserSubscription record associated with the Subscription.
     */
    public function userSubscription() {
        
        return $this->hasMany(UserSubscription::class, 'subscription_id');
    }

    /**
     * Get the User record associated with the Subscription.
     */
    public function user() {
        
        return $this->hasMany(User::class, 'user_id');
    }

	/**
     * Scope a query to basic subscription details
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeBaseResponse($query) {

        $currency = \Setting::get('currency' , '$');

        return $query->select('subscriptions.id as subscription_id', 
                'subscriptions.title', 
                'subscriptions.description', 
                'subscriptions.plan',
                'subscriptions.amount', 
                'subscriptions.popular_status', 
                'subscriptions.status', 
                'subscriptions.created_at' , 
                \DB::raw("'$currency' as currency")
                );
    }

    /**
     * Scope a query to basic subscription details
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeApproved($query) {

        return $query->where('subscriptions.status', APPROVED);
    }
}

resources/views/admin/subscriptions/_form.blade.php
<div class="card-body">

    @if(Setting::get('is_demo_control_enabled') == NO )

        <form  method="POST" action="{{route('admin.subscriptions.save')}}" enctype="multipart/form-data" role="form">

    @else

        <form class="forms-sample" role="form">

    @endif

        @csrf

        <div class="form-body">

            <h3 class="card-title">{{tr('subscriptions')}}</h3>

            <hr>

            <input type="hidden" name="subscription_id" value="{{ $subscription_details->id }}">

            <div class="row p-t-20">

                <div class="form-group col-md-6">

                    <label class="control-label">{{ tr('title') }}<span class="admin-required">*</span></label>
                    <input type="text" required name="title" class="form-control" id="title" value="{{$subscription_details->title ?? old('title') }}" placeholder="{{ tr('title') }}" pattern = "[a-zA-Z,0-9\s\-\.]{2,100}">
                     
                </div>

                <div class="form-group col-md-6">

                    <label class="control-label">{{tr('description')}}<span class="admin-required">*</span></label>
                    <textarea class="form-control" name="description" required placeholder="{{ tr('description') }}">{{$subscription_details->description ?? old('description') }}</textarea>
                    
                </div>

                <div class="form-group col-md-6">

                    <label class="control-label">{{tr('no_of_months')}}<span class="admin-required">*</span></label>
                    <input type="number" min="1" max="12" pattern="[0-9][0-2]{2}"  required name="plan" class="form-control" id="plan" value="{{ $subscription_details->plan ?? old('plan') }}" title="{{ tr('please_enter_plan_month') }}" placeholder="{{ tr('no_of_months') }}">
                    
                </div>

                <div class="form-group col-md-6">

                    <label class="control-label">{{tr('no_of_users')}}<span class="admin-required">*</span></label>
                    <input type="number" required value="{{$subscription_details->no_of_users ?? old('no_of_users') }}" name="no_of_users" class="form-control" id="no_of_users" placeholder="{{ tr('no_of_users') }}" step="any">
                    
                </div>

                <div class="form-group col-md-6">

                    <label class="control-label">{{tr('no_of_hrs')}}<span class="admin-required">*</span></label>
                    <input type="number" required value="{{$subscription_details->no_of_hrs ?? old('no_of_hrs') }}" name="no_of_hrs" class="form-control" id="no_of_hrs" placeholder="{{ tr('no_of_hrs') }}" step="any">
                    
                </div>


                <div class="form-group col-md-6">

                    <label class="control-label">{{tr('amount')}}<span class="admin-required">*</span></label>
                    <input type="number" required value="{{$subscription_details->amount ??  old('amount')}}" name="amount" class="form-control" id="amount" placeholder="{{ tr('amount') }}" step="any">
                    
                </div>


            </div>

        </div>

        <div class="form-actions">

            @if(Setting::get('is_demo_control_enabled') == NO )

                <button type="submit" class="btn btn-primary btn-pill pull-right"> <i class="fa fa-check"></i>{{tr('save')}}</button>

            @else

                <button type="button" class="btn btn-primary btn-pill pull-right"> <i class="fa fa-check"></i>{{tr('save')}}</button>
                
            @endif

            <button type="reset" class="btn reset-btn btn-pill">{{tr('reset')}}</button>

        </div>

    </form>

</div>

resources/views/admin/subscriptions/create.blade.php
@extends('layouts.admin')

@section('page_header',tr('subscriptions'))

@section('styles')

<link rel="stylesheet" href="{{asset('admin-assets/css/dropify.min.css')}}">

<link href="{{asset('admin-assets/css/datepicker.css')}}" rel="stylesheet">

@endsection

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.subscriptions.index')}}">{{tr('subscriptions')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)" aria-current="page"></a><span>{{tr('add_subscription')}}</span></li>

@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('add_subscription')}}

            <a class="btn btn-secondary pull-right" href="{{route('admin.subscriptions.index')}}">
                <i class="fa fa-eye"></i> {{tr('view_subscriptions')}}
            </a>
        </h4>

    </div>

    @include('admin.subscriptions._form')

</div>

@endsection

resources/views/admin/subscriptions/index.blade.php
@extends('layouts.admin')

@section('page_header',tr('subscriptions'))

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.subscriptions.index')}}">{{tr('subscriptions')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)"></a>{{tr('view_subscriptions')}}</li>

@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('view_subscriptions')}}

            <a class="btn btn-secondary pull-right" href="{{route('admin.subscriptions.create')}}">
                <i class="fa fa-plus"></i> {{tr('add_subscription')}}
            </a>
        </h4>

    </div>

	<div class="card-body">

		<div class="table-responsive">

            @if(count($subscriptions) > 0)

                <table id="dataTable" class="table data-table">

                    <thead>
                        <tr>
                            <th>{{ tr('s_no') }}</th>
                            <th>{{ tr('title') }}</th>
                            <th>{{ tr('no_of_months') }}</th>
                            <th>{{ tr('amount') }}</th>
                            <th>{{ tr('status') }}</th>
                            <th>{{ tr('no_of_users') }}</th>
                            <th>{{ tr('no_of_hrs') }}</th>
                            <th>{{ tr('subscribers') }}</th>
                            <th>{{ tr('action') }}</th>
                        </tr>
                    </thead>

                    <tbody>

                    	@foreach($subscriptions as $i => $subscription_details)
                            <tr>
                                <td>{{$i+$subscriptions->firstItem()}}</td>

                                <td>
                                    <a href="{{ route('admin.subscriptions.view' , ['subscription_id' => $subscription_details->id] ) }}">{{ $subscription_details->title }}</a>
                                </td>

                                <td>{{formatted_plan($subscription_details->plan,$subscription_details->subscription_type)}}</td>

                                <td>{{formatted_amount($subscription_details->amount)}}</td>

                                <td>
                                    @if($subscription_details->status ==  YES)
                                        <span class="badge badge-success">{{tr('approved')}}
                                        </span>
                                    @else
                                        <span class="badge badge-danger">{{tr('declined')}}</span> 
                                    @endif
                                </td>

                                <td>{{$subscription_details->no_of_users_formatted}}</td>

                                <td>{{$subscription_details->no_of_hrs_formatted}}</td>

                                <td>
                                    <a href="{{ route('admin.subscription.payments' , ['subscription_id' => $subscription_details->id] ) }}">{{ $subscription_details->subscribers_count }}</a>
                                    
                                </td>

                                <td>
                                    
                                    <div class="dropdown">

                                        <button class="btn btn-outline-primary  dropdown-toggle btn-sm" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{tr('action')}}
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">
                                          
                                            <a class="dropdown-item" href="{{ route('admin.subscriptions.view', ['subscription_id' => $subscription_details->id]) }}">
                                                {{tr('view')}}
                                            </a>
                                            
                                            @if(Setting::get('is_demo_control_enabled') == NO)

                                                <a class="dropdown-item" href="{{ route('admin.subscriptions.edit', ['subscription_id' => $subscription_details->id]) }}">
                                                    {{tr('edit')}}
                                                </a>
                                                
                                                <a class="dropdown-item" href="{{route('admin.subscriptions.delete', ['subscription_id' => $subscription_details->id])}}" 
                                                onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $subscription_details->name)}}&quot;);">
                                                    {{tr('delete')}}
                                                </a>
                                            @else

                                                <a class="dropdown-item" href="javascript:;">{{tr('edit')}}</a>
                                              
                                                <a class="dropdown-item" href="javascript:;">{{tr('delete')}}</a>                           
                                            @endif
                                            

                                            @if($subscription_details->status == USER_APPROVED)

                                                <a class="dropdown-item" href="{{ route('admin.subscriptions.status', ['user_id' => $subscription_details->id]) }}" onclick="return confirm(&quot;{{$subscription_details->first_name}} - {{tr('user_decline_confirmation')}}&quot;);" >
                                                    {{ tr('decline') }} 
                                                </a>

                                            @else
                                                
                                                <a class="dropdown-item" href="{{ route('admin.subscriptions.status', ['user_id' => $subscription_details->id]) }}">
                                                    {{ tr('approve') }} 
                                                </a>
                                                   
                                            @endif

                                        </div>

                                    </div>

                                </td>
                             
                            </tr>
                        @endforeach
                       
                    </tbody>
                    
                </table>

                <div class="pull-right">{{ $subscriptions->links() }}</div>

            @else

                <h3 class="no-result">{{ tr('no_subscriptions_found') }}</h3>
                
            @endif

        </div>
        
	</div>
	
</div>

@endsection

resources/views/admin/subscriptions/user_subscriptions.blade.php
@extends('layouts.admin')

@section('page_header',tr('subscriptions'))

@section('breadcrumbs')


<li class="breadcrumb-item"><a href="{{route('admin.users.index')}}">{{tr('users')}}</a></li>

<li class="breadcrumb-item"><a href="javascript:void(0)"></a>{{tr('view_users')}}</li>

<li class="breadcrumb-item active"><a href="{{route('admin.subscriptions.index')}}">{{tr('subscriptions')}}</a></li>

@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('user_subscriptions')}}</h4>

    </div>

    <div class="card-body">

        <div class="table-responsive">

            @if(count($user_subscriptions) > 0)

            <table id="dataTable" class="table data-table">

                <thead>
                    <tr>
                        <th>{{ tr('s_no') }}</th>
                        <th>{{ tr('subscriptions') }}</th>
                        <th>{{ tr('payment_id') }}</th>
                        <th>{{ tr('amount') }}</th>
                        <th>{{ tr('mode') }}</th>
                        <th>{{ tr('is_current') }}</th>
                        <th>{{ tr('expiry_date') }}</th>
                        <th>{{ tr('status') }}</th>
                        <th>{{ tr('created_at') }}</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach($user_subscriptions as $i => $subscription_details)
                    <tr>
                        <td>{{ $i+$user_subscriptions->firstItem() }}</td>

                        <td>
                            <a href="{{ route('admin.subscriptions.view' , ['subscription_id' => $subscription_details->subscription_id] ) }}">{{ $subscription_details->title }}</a>
                        </td>

                        <td>{{ $subscription_details->payment_id }}</td>

                        <td>{{formatted_amount($subscription_details->amount)}}</td>

                        <td>{{ $subscription_details->payment_mode }}</td>

                        <td>
                            @if($subscription_details->is_current_subscription == YES)
                            <span class="badge badge-success">{{tr('yes')}}
                            </span>
                            @else
                            <span class="badge badge-danger">{{tr('no')}}</span>
                            @endif
                        </td>

                        <td>{{ $subscription_details->expiry_date }}</td>

                        <td>
                            @if($subscription_details->status == YES)
                            <span class="badge badge-success">{{tr('paid')}}
                            </span>
                            @else
                            <span class="badge badge-danger">{{tr('pending')}}</span>
                            @endif
                        </td>
                        <td>{{ common_date($subscription_details->created_at, Auth::guard('admin')->user()->timezone,'Y-m-d H:i:s')  }}</td>

                    </tr>
                    @endforeach

                </tbody>

            </table>

            <div class="pull-right">{{ $user_subscriptions->links() }}</div>

            @else

            <h3 class="no-result">{{ tr('no_subscriptions_found') }}</h3>

            @endif

        </div>

    </div>

</div>

<div class="row top_css">

    @if(count($subscriptions) > 0)

    @foreach($subscriptions as $s => $subscription_details)

    <div class="col-md-4">

        <div class="card" style="margin-bottom: 20px">

            <div class="card-body">
                <h5 class="card-title">
                    <a href="{{ route('admin.subscriptions.view' , ['subscription_id' => $subscription_details->id] ) }}" target="_blank">{{ $subscription_details->title }}</a>
                </h5>
                <p class="card-text"><?php echo $subscription_details->description; ?></p>
            </div>
            <ul class="list-group list-group-flush">

                <li class="list-group-item">{{formatted_amount($subscription_details->amount) }} / {{ formatted_plan($subscription_details->plan ?? 0) }} </li>

                <li class="list-group-item">{{ tr('no_of_users') }} : {{ $subscription_details->no_of_users }}</li>

            </ul>
            <div class="card-body">
                <a href="{{ route('admin.users.subscriptions.save', ['subscription_id' => $subscription_details->id, 'user_id' => $user_details->id]) }}" class="card-link ">{{ tr('choose') }}</a>
            </div>

        </div>

    </div>

    @endforeach

    @endif

</div>


@endsection

resources/views/admin/subscriptions/view.blade.php
@extends('layouts.admin')

@section('page_header',tr('subscriptions'))

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.subscriptions.index')}}">{{tr('subscriptions')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)"></a>{{tr('view_subscriptions')}}</li>
@endsection

@section('content')

<div class="card">

	<div class="card-header bg-info"> 

		<h4 class="m-b-0 text-white">{{tr('view_subscriptions')}}</h4>

	</div>

    <div class="card-body">

    	<div class="row">

            <div class="col-6">

                <!-- Card content -->
                <div class="card-body">

                    <div class="template-demo">

                        <table class="table mb-0">

                          <thead>
                           
                          </thead>

                          <tbody>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('title') }}</b></td>
                                <td class="pr-0 text-right"><div>{{$subscription_details->title}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('no_of_months') }}</b></td>
                                <td class="pr-0 text-right"><div>{{formatted_plan($subscription_details->plan,$subscription_details->subscription_type)}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('amount') }}</b></td>
                                <td class="pr-0 text-right"><div>{{formatted_amount($subscription_details->amount)}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('no_of_hrs') }}</b></td>
                                <td class="pr-0 text-right"><div>{{$subscription_details->no_of_hrs_formatted}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('no_of_users') }}</b></td>
                                <td class="pr-0 text-right"><div>{{$subscription_details->no_of_users_formatted}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('subscribers') }}</b></td>
                                 <td class="pr-0 text-right">
                                    <a href="{{ route('admin.subscriptions.users' , ['subscription_id' => $subscription_details->id] ) }}">{{ $total_subscribers }}</a>
                                </td>
                            </tr>

                            <tr>

                              <td class="pl-0"> <b>{{ tr('status') }}</b></td>

                              <td class="pr-0 text-right">

                                    @if($subscription_details->status == USER_PENDING)

                                        <span class="card-text badge badge-danger badge-md text-uppercase">{{tr('pending')}}</span>

                                    @elseif($subscription_details->status == USER_APPROVED)

                                        <span class="card-text  badge badge-success badge-md text-uppercase">{{tr('approved')}}</span>

                                    @else

                                        <span class="card-text label label-rouded label-menu label-danger">{{tr('declined')}}</span>

                                    @endif

                              </td>

                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('created_at') }}</b></td>
                                <td class="pr-0 text-right"><div>{{ common_date($subscription_details->created_at, Auth::guard('admin')->user(),'d M Y H:i:s') }}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('updated_at') }}</b></td>
                                <td class="pr-0 text-right"><div>{{ common_date($subscription_details->updated_at,Auth::guard('admin')->user(),'d M Y H:i:s') }}</div></td>
                            </tr>

                          </tbody>

                        </table>

                    </div>

                </div>

            </div>

    		<div class="col-6">

                <div class="row">

                    @if($subscription_details->description)

                        <h5 class="col-md-12">{{tr('description')}}</h5>
                        <p class="col-md-12 text-muted text-word-wrap">{{$subscription_details->description}}</p>

                    @endif
                    
                </div>
                <hr>
				<div class="row">

                    <div class="col-6">

                        @if(Setting::get('is_demo_control_enabled') == YES)

                            <a href="javascript:;" class="btn btn-primary btn-block">{{tr('edit')}}</a>

                            <a href="javascript:;" class="btn btn-danger btn-block">{{tr('delete')}}</a>

                        @else

                            <a class="btn btn-primary btn-block" href="{{ route('admin.subscriptions.edit', ['subscription_id' => $subscription_details->id])}}">{{tr('edit')}}</a>

                            <a class="btn btn-danger btn-block" href="{{route('admin.subscriptions.delete', ['subscription_id' => $subscription_details->id])}}" onclick="return confirm(&quot;{{tr('subscription_delete_confirmation' , $subscription_details->title)}}&quot;);">{{tr('delete')}}</a>

                        @endif

                    </div>

                    <div class="col-6">

                    	@if($subscription_details->status == USER_APPROVED)

                            <a class="btn btn-danger btn-block" href="{{ route('admin.subscriptions.status', ['subscription_id' => $subscription_details->id]) }}" onclick="return confirm(&quot;{{$subscription_details->title}} - {{tr('subscription_decline_confirmation')}}&quot;);" >
                                {{ tr('decline') }} 
                            </a>

                        @else
                            
                            <a class="btn btn-success btn-block" href="{{ route('admin.subscriptions.status', ['subscription_id' => $subscription_details->id]) }}">
                                {{ tr('approve') }} 
                            </a>
                               
                        @endif

                    </div> 

                </div>

    		</div>

            

        </div>

    </div>

</div>

@endsection