routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/meetings_clear', 'AdminController@users_meetings_clear')->name('users.meetings_clear');


        // settings

        Route::get('/admin-control', 'AdminController@admin_control')->name('control');

        Route::get('/ios-control', 'AdminController@ios_control')->name('ios-control'); 

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        Route::get('/subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        // Route::get('/subscription/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

        Route::get('/subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('/subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('/subscriptions/create', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('/subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('/subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('/subscriptions/status', 'AdminController@subscriptions_status_change')->name('subscriptions.status');

        Route::get('/subscriptions/popular/status', 'AdminController@subscriptions_popular_status')->name('subscriptions.popular.status');

        Route::get('/subscriptions/users', 'AdminController@subscriptions_users')->name('subscriptions.users');

        Route::get('subscriptions/payments' , 'AdminController@subscription_payments')->name('subscription.payments');

        Route::get('meetings' , 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');
       
        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');
        
        Route::get('meetings/end', 'AdminController@meetings_end')->name('meetings.end');

        //User Subscriptions

        Route::get('/users/subscriptions/', 'AdminController@users_subscriptions_index')->name('users.subscriptions');

        Route::get('/users/subscriptions/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

        Route::get('/users/subscriptions/view' , 'AdminController@user_subscriptions_view')->name('users.subscriptions.view');


    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

use Setting, DB;

use App\Helpers\Helper;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeCommonResponse($query) {

        return $query->select(
            'users.id as user_id',
            'users.username as username',
            'users.name',
            'users.email as email',
            'users.picture as picture',
            'users.description as description',
            'users.mobile as mobile',
            'users.token as token',
            'users.token_expiry as token_expiry',
            'users.social_unique_id as social_unique_id',
            'users.login_by as login_by',
            'users.payment_mode',
            'users.user_card_id',
            'users.status as user_status',
            'users.email_notification_status',
            'users.push_notification_status',
            'users.is_verified',
            'users.user_type',
            'users.registration_steps',
            'users.created_at',
            'users.updated_at'
            );
    
    }

    /**
     * Scope a query to only include active users.
     *
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeOtherCommonResponse($query) {

        return $query->select(
            'users.id as user_id',
            'users.username as username',
            'users.name',
            'users.email as email',
            'users.picture as picture',
            'users.mobile as mobile',
            'users.description as description',
            'users.full_address as full_address',
            'users.work',
            'users.school',
            'users.languages',
            'users.social_unique_id as social_unique_id',
            'users.status as user_status',
            'users.is_verified',
            'users.user_type',
            DB::raw("DATE_FORMAT(users.created_at, '%M %Y') as joined") ,
            'users.created_at',
            'users.updated_at'
            );

    }

    /**
     * Get the UserSubscription record associated with the user.
     */
    public function userSubscription() {
        
        return $this->hasMany(UserSubscription::class, 'user_id');
    }    

    /**
     * Get the Meeting record associated with the user.
     */
    public function userMeeting() {
        
        return $this->hasMany(Meeting::class, 'user_id');
    }

    /**
     * Get the UserCard record associated with the user.
     */
    public function userCard() {
        
        return $this->hasMany(UserCard::class, 'user_id');
    }

    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

            $model->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                if($model->attributes['login_by'] == 'manual') {

                    $model->generateEmailCode();

                }

            }

            $model->attributes['status'] = USER_APPROVED;

            $model->attributes['payment_mode'] = COD;

            $model->attributes['username'] = routefreestring($model->attributes['name']);

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = Helper::generate_token();

            $model->attributes['token_expiry'] = Helper::generate_token_expiry();

            if(in_array($model->attributes['login_by'], ['facebook' , 'google'])) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['unique_id'] = "UID"."-".$model->attributes['id']."-".uniqid();

            $model->save();

            /**
             * @todo Update total number of users 
             */
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = routefreestring($model->attributes['name']);

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

        });

        static::deleting(function ($model){

            Helper::delete_file($model->picture , PROFILE_PATH_USER);

            foreach ($model->userSubscription as $key => $user_subscription) {
                
                $user_subscription->delete();
            }

            foreach ($model->userMeeting as $key => $user_meeting) {
                
                $user_meeting->delete();
            }

            foreach ($model->userCard as $key => $user_card) {
                
                $user_card->delete();
            }

        });

    }

    /**
     * Generates Token and Token Expiry
     * 
     * @return bool returns true if successful. false on failure.
     */

    protected function generateEmailCode() {

        $this->attributes['verification_code'] = Helper::generate_email_code();

        $this->attributes['verification_code_expiry'] = Helper::generate_email_expiry();

        // Check Email verification controls and email configurations

        if(Setting::get('is_account_email_verification') == YES && Setting::get('is_email_notification') == YES && Setting::get('is_email_configured') == YES) {

            $this->attributes['is_verified'] = 0;

        } else { 

            $this->attributes['is_verified'] = 1;
        }

        return true;
    
    }

   
}

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('page_header',tr('users'))

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.users.index')}}">{{tr('users')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)"></a>{{tr('view_users')}}</li>

@endsection

@section('content')

<div class="card">

    <div class="card-header bg-info">

        <h4 class="m-b-0 text-white">{{tr('view_users')}}

            <button type="button" class="btn mb-2 btn-success" data-toggle="popover" data-content="{{tr('users_note')}}">{{tr('help')}}</button>
    
            <a class="btn btn-secondary pull-right" href="{{route('admin.users.create')}}">
                <i class="fa fa-plus"></i> {{tr('add_user')}}
            </a>
        </h4>

    </div>

	<div class="card-body">

		<div class="table-responsive">

            @if(count($users) > 0)

                <table id="dataTable" class="table data-table">

                    <thead>
                        <tr>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('name')}}</th>
                            <th>{{tr('email')}}</th>
                            <th>{{tr('mobile')}}</th>
                            <th>{{tr('meetings_clear')}}</th>
                            <th>{{tr('status')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>

                    <tbody>

                    	@foreach($users as $i => $user_details)
                            
                            <tr>
                                <td>{{$i+$users->firstItem()}}</td>

                                <td>
                                    <a href="{{ route('admin.users.view', ['user_id' => $user_details->id]) }}"><img
                                            src="{{$user_details->picture ?? asset('placeholder.jpg')}}" alt="user" width="40"
                                            class="img-circle" />{{$user_details->name}}
                                    </a>
                                </td>

                                <td>
                                	{{$user_details->email}}
                                </td>

                                <td>{{$user_details->mobile}}</td>

                                <td>
                                @if(strpos($user_details->is_cleared,tr('clear')) !== false)

                                <a href="{{route('admin.users.meetings_clear',['user_id'=>$user_details->id])}}" 
                                    onclick="return confirm('Are you sure about ongoing meetings clear?')"
                                >{{$user_details->is_cleared}}
                               </a>

                                @else
                                
                                    <a href="javascript:void(0)">{{$user_details->is_cleared}}</a>
                                @endif
                               </td>

                                <td>
                                    @if($user_details->status ==  YES)
                                        <span class="badge badge-success">{{tr('approved')}}
                                        </span>
                                    @else
                                        <span class="badge badge-danger">{{tr('declined')}}</span> 
                                    @endif
                                </td>

                                <td>
                                    
                                    <div class="dropdown">

                                        <button class="btn btn-outline-primary  dropdown-toggle btn-sm" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{tr('action')}}
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">
                                          
                                            <a class="dropdown-item" href="{{ route('admin.users.view', ['user_id' => $user_details->id]) }}">
                                                {{tr('view')}}
                                            </a>
                                            
                                            @if(Setting::get('is_demo_control_enabled') == NO)

                                                <a class="dropdown-item" href="{{ route('admin.users.edit', ['user_id' => $user_details->id]) }}">
                                                    {{tr('edit')}}
                                                </a>
                                                
                                                <a class="dropdown-item" href="{{route('admin.users.delete', ['user_id' => $user_details->id])}}" 
                                                onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">
                                                    {{tr('delete')}}
                                                </a>
                                            @else

                                                <a class="dropdown-item" href="javascript:;">{{tr('edit')}}</a>
                                              
                                                <a class="dropdown-item" href="javascript:;">{{tr('delete')}}</a>                           
                                            @endif
                                            
                                            <div class="dropdown-divider"></div>

                                            @if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED) 

                                                <a class="dropdown-item" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> {{ tr('verify') }} 
                                                </a>

                                            @endif 

                                            @if($user_details->status == USER_APPROVED)

                                                <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}" onclick="return confirm(&quot;{{$user_details->first_name}} - {{tr('user_decline_confirmation')}}&quot;);" >
                                                    {{ tr('decline') }} 
                                                </a>

                                            @else
                                                
                                                <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}">
                                                    {{ tr('approve') }} 
                                                </a>
                                                   
                                            @endif

                                            <a class="dropdown-item" href="{{ route('admin.meetings.index', ['user_id' => $user_details->id]) }}">
                                                {{ tr('meetings') }} 
                                            </a>

                                            <a class="dropdown-item" href="{{ route('admin.users.subscriptions' , ['user_id' => $user_details->id] ) }}">		
                                                {{ tr('subscription_plans') }}
                                            </a>


                                        </div>

                                    </div>

                                </td>
                             
                            </tr>
                        @endforeach
                       
                    </tbody>
                    
                </table>

                <div class="pull-right">{{ $users->links() }}</div>

            @else

                <h3 class="no-result">{{ tr('no_user_found') }}</h3>
                
            @endif

        </div>
        
	</div>
	
</div>

@endsection

resources/views/admin/users/view.blade.php
@extends('layouts.admin')

@section('page_header',tr('users'))

@section('breadcrumbs')

<li class="breadcrumb-item"><a href="{{route('admin.users.index')}}">{{tr('users')}}</a></li>

<li class="breadcrumb-item active"><a href="javascript:void(0)"></a>{{tr('view_users')}}</li>
@endsection

@section('content')

<div class="card">

	<div class="card-header bg-info"> 

		<h4 class="m-b-0 text-white">{{tr('view_users')}}</h4>

	</div>

    <div class="card-body">

    	<div class="row">

    		<div class="col-6">

    			<img src="{{$user_details->picture}}" style="width: 100%; height: 50%">
    			<hr>

    				<div class="row">

                        <div class="col-6">

                            @if(Setting::get('is_demo_control_enabled') == YES)

                                <a href="javascript:;" class="btn btn-primary btn-block">{{tr('edit')}}</a>

                                <a href="javascript:;" class="btn btn-danger btn-block">{{tr('delete')}}</a>

                            @else

                                <a class="btn btn-primary btn-block" href="{{ route('admin.users.edit', ['user_id' => $user_details->id])}}">{{tr('edit')}}</a>

                                <a class="btn btn-danger btn-block" href="{{route('admin.users.delete', ['user_id' => $user_details->id])}}" onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">{{tr('delete')}}</a>

                            @endif

                        </div>

                        <div class="col-6">

                        	@if($user_details->status == USER_APPROVED)

                                <a class="btn btn-danger btn-block" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}" onclick="return confirm(&quot;{{$user_details->first_name}} - {{tr('user_decline_confirmation')}}&quot;);" >
                                    {{ tr('decline') }} 
                                </a>

                            @else
                                
                                <a class="btn btn-success btn-block" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}">
                                    {{ tr('approve') }} 
                                </a>
                                   
                            @endif


                            @if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED) 

                                <a class="btn btn-primary btn-block" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> {{ tr('verify') }} 
                                </a>   

                            @endif

                            <a class="btn btn-primary btn-block" href="{{ route('admin.meetings.index', ['user_id' => $user_details->id]) }}">
                                {{ tr('meetings') }} 
                            </a>

                            <a class="btn btn-primary btn-block" target="_blank" href="{{route('admin.users.subscriptions', ['user_id' => $user_details->id] )}}" class="btn btn-xs btn-success">{{tr('subscribe')}}</a>

                        </div> 

                    </div>

                <hr>

                <div class="row">

                    @if($user_details->description)

                        <h5 class="col-md-12">{{tr('description')}}</h5>
                     	<p class="col-md-12 text-muted text-word-wrap">{{$user_details->description}}</p>

                    @endif
                    
                </div>

    		</div>

            <div class="col-6">

                <!-- Card content -->
                <div class="card-body">

                    <div class="template-demo">

                        <table class="table mb-0">

                          <thead>
                           
                          </thead>

                          <tbody>

                            <tr>
                                <td class="pl-0"><b>{{ tr('name') }}</b></td>
                                <td class="pr-0 text-right"><div >{{$user_details->name}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"><b>{{ tr('email') }}</b></td>
                                <td class="pr-0 text-right"><div >{{$user_details->email}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"><b>{{ tr('mobile') }}</b></td>
                                <td class="pr-0 text-right"><div >{{$user_details->mobile ?:tr('not_available')}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"><b>{{ tr('gender') }}</b></td>
                                <td class="pr-0 text-right"><div >{{$user_details->gender}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"><b>{{ tr('dob') }}</b></td>
                                <td class="pr-0 text-right"><div >{{common_date($user_details->dob,Auth::guard('admin')->user()->timezone,'d M Y')}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"><b>{{ tr('device_type') }}</b></td>
                                <td class="pr-0 text-right"><div >{{$user_details->device_type}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"><b>{{ tr('login_by') }}</b></td>
                                <td class="pr-0 text-right"><div>{{ $user_details->login_by }}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"><b>{{ tr('register_type') }} </b></td>
                                <td class="pr-0 text-right"><div>{{ $user_details->register_type }}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"><b>{{ tr('payment_mode') }} </b></td>
                                <td class="pr-0 text-right"><div >{{$user_details->payment_mode}}</div></td>
                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('timezone') }}</b></td>
                                <td class="pr-0 text-right"><div>{{$user_details->timezone}}</div></td>
                            </tr>

                            <tr>

                              <td class="pl-0"> <b>{{ tr('status') }}</b></td>

                              <td class="pr-0 text-right">

                                    @if($user_details->status == USER_PENDING)

                                        <span class="card-text badge badge-danger badge-md text-uppercase">{{tr('pending')}}</span>

                                    @elseif($user_details->status == USER_APPROVED)

                                        <span class="card-text  badge badge-success badge-md text-uppercase">{{tr('approved')}}</span>

                                    @else

                                        <span class="card-text label label-rouded label-menu label-danger">{{tr('declined')}}</span>

                                    @endif

                              </td>

                            </tr>

                            <tr> 

                                <td class="pl-0"><b>{{ tr('is_email_verified') }}</b></td>
                                
                                <td class="pr-0 text-right">

                                    @if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED)

                                        <span class="card-text label label-rouded label-menu label-danger">{{ tr('no') }}</span>

                                    @else

                                        <span class="card-text badge badge-success badge-md text-uppercase">{{ tr('yes') }}</span>

                                    @endif
                                </td>

                            </tr>

                            <tr> 

                                <td class="pl-0"><b>{{ tr('push_notification') }}</b></td>
                                
                                <td class="pr-0 text-right">

                                    @if($user_details->push_notification_status)

                                        <span class="card-text label label-rouded label-menu label-danger">{{ tr('on') }}</span>

                                    @else

                                        <span class="card-text badge badge-success badge-md text-uppercase">{{ tr('off') }}</span>

                                    @endif
                                </td>

                            </tr>

                            <tr> 

                                <td class="pl-0"><b>{{ tr('email_notification') }}</b></td>
                                
                                <td class="pr-0 text-right">

                                    @if($user_details->email_notification_status)

                                        <span class="card-text label label-rouded label-menu label-danger">{{ tr('on') }}</span>

                                    @else

                                        <span class="card-text badge badge-success badge-md text-uppercase">{{ tr('off') }}</span>

                                    @endif
                                </td>

                            </tr>

                            <tr>
                                <td class="pl-0"> <b>{{ tr('created_at') }}</b></td>
                                <td class="pr-0 text-right"><div>{{ common_date($user_details->created_at, Auth::guard('admin')->user()->timezone,'d M Y H:i:s') }}</div></td>
                            </tr>

                            <tr>`
                                <td class="pl-0"> <b>{{ tr('updated_at') }}</b></td>
                                <td class="pr-0 text-right"><div>{{ common_date($user_details->updated_at,Auth::guard('admin')->user()->timezone, 'd M Y H:i:s') }}</div></td>
                            </tr>

                          </tbody>

                        </table>

                    </div>

                </div>

            </div>

        </div>

    </div>

</div>

@endsection