routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/meetings_clear', 'AdminController@users_meetings_clear')->name('users.meetings_clear');


        // settings

        Route::get('/admin-control', 'AdminController@admin_control')->name('control');

        Route::get('/ios-control', 'AdminController@ios_control')->name('ios-control'); 

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 

        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        Route::get('/subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        // Route::get('/subscription/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

        Route::get('/subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('/subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('/subscriptions/create', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('/subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('/subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('/subscriptions/status', 'AdminController@subscriptions_status_change')->name('subscriptions.status');

        Route::get('/subscriptions/popular/status', 'AdminController@subscriptions_popular_status')->name('subscriptions.popular.status');

        Route::get('/subscriptions/users', 'AdminController@subscriptions_users')->name('subscriptions.users');

        Route::get('subscriptions/payments' , 'AdminController@subscription_payments')->name('subscription.payments');

        Route::get('meetings' , 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');
       
        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');
        
        Route::get('meetings/end', 'AdminController@meetings_end')->name('meetings.end');

        //User Subscriptions

        Route::get('/users/subscriptions/', 'AdminController@users_subscriptions_index')->name('users.subscriptions');

        Route::get('/users/subscriptions/save', 'AdminController@users_subscriptions_save')->name('users.subscriptions.save');

        Route::get('/users/subscriptions/view' , 'AdminController@user_subscriptions_view')->name('users.subscriptions.view');


    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/admin/_logout_model.blade.php
<div class="modal fade" id="logoutModel" tabindex="-1" role="dialog" aria-labelledby="logoutModel" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered" role="document">

        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title" id="logoutModelTitle">{{tr('confirm_logout')}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <div class="modal-body">
                <h5>{{tr('logout_note')}}</h5>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-pill" data-dismiss="modal">{{tr('close')}}</button>
                <a class="btn btn-primary btn-pill" href="{{route('admin.logout')}}">{{tr('logout')}}</a>
            </div>

        </div>

    </div>
    
</div>

resources/views/layouts/admin/focused.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <title>{{Setting::get('site_name')}}</title>

    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Favicon icon -->
    <link rel="shortcut icon" href="{{ Setting::get('site_icon') }}" />

    <!-- Custom CSS -->
    <link href="{{asset('admin-assets/css/style.css')}}" rel="stylesheet">

    <!-- Toast CSS -->
    <link href="{{asset('admin-assets/plugins/toaster/toastr.min.css')}}" rel="stylesheet" />


    @include('layouts.admin.scripts')

    <?php echo Setting::get('header_scripts'); ?>
   
</head>

<body>

    @yield('content')


    <?php echo Setting::get('google_analytics'); ?>

    <?php echo Setting::get('body_scripts'); ?>
    
</body>

</html>

resources/views/layouts/admin/footer.blade.php
<footer class="footer mt-auto">
   
    <div class="copyright bg-white">
        <p>
             {{tr('copy_right')}} &copy; {{date('Y')}} <a class="text-primary" href="{{Setting::get('frontend_url')}}" target="_blank">{{Setting::get('site_name' , 'StreamZoom')}}</a>. {{tr('all_rights')}}
        </p>
    </div>
    
</footer>

resources/views/layouts/admin/header.blade.php
<header class="main-header" id="header">

    <nav class="navbar navbar-expand-lg navbar-light" id="navbar">
        
        <button id="sidebar-toggler" class="sidebar-toggle">
            <span class="sr-only">Toggle navigation</span>
        </button>


        <div class="navbar-right ">

           
           
            <ul class="nav navbar-nav">

                 <li class="nav-item d-none d-lg-block">
                <a class="btn btn-primary btn-fw" id="visit-website" href="{{Setting::get('frontend_url')}}" target="_blank">
                    Visit Website
                </a>
            </li>
              
                <li class="dropdown user-menu">

                    <button class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <img src="{{Auth::guard('admin')->user()->picture ?? '-'}}" class="user-image rounded-circle header-profile-image" />
                        <span class="d-none d-lg-inline-block">{{Auth::guard('admin')->user()->name ?? '-'}}</span>
                    </button>

                    <ul class="dropdown-menu dropdown-menu-right">
                        <li>
                            <a class="dropdown-link-item" href="{{route('admin.profile')}}">
                                <i class="mdi mdi-account-outline"></i>
                                <span class="nav-text">{{tr('my_profile')}}</span>
                            </a>
                        </li>

                        <li class="dropdown-footer">
                            <a class="dropdown-link-item"  data-toggle="modal" data-target="#logoutModel"> <i class="mdi mdi-logout pull-left"></i> {{tr('logout')}}</a>
                        </li>
                    </ul>

                </li>

            </ul>

        </div>

    </nav>

</header>

resources/views/layouts/admin/scripts.blade.php
<script src="{{asset('admin-assets/plugins/jquery/jquery.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/simplebar/simplebar.min.js')}}"></script>

<script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>

<script src="{{asset('admin-assets/plugins/apexcharts/apexcharts.js')}}"></script>

<script src="{{asset('admin-assets/plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/jvectormap/jquery-jvectormap-2.0.3.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/jvectormap/jquery-jvectormap-world-mill.js')}}"></script>

<script src="{{asset('admin-assets/plugins/nprogress/nprogress.js')}}"></script>

<script src="{{asset('admin-assets/plugins/jvectormap/jquery-jvectormap-us-aea.js')}}"></script>

<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<script src="{{asset('admin-assets/plugins/toaster/toastr.min.js')}}"></script>

<script src="{{asset('admin-assets/js/mono.js')}}"></script>

<script src="{{asset('admin-assets/js/chart.js')}}"></script>

<script src="{{asset('admin-assets/js/map.js')}}"></script>

<script src="{{asset('admin-assets/js/select2.min.js')}}"></script>

<script src="{{asset('admin-assets/js/custom.js')}}"></script>



<script src="{{asset('admin-assets/plugins/daterangepicker/moment.min.js')}}"></script>

<script src="{{asset('admin-assets/plugins/daterangepicker/daterangepicker.js')}}"></script>

<script src="http://cdn.ckeditor.com/4.5.5/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'ckeditor' );

    $(document).ready(function() {
        $('.select2').select2();
    });


  

</script>

resources/views/layouts/admin/sidebar.blade.php
<aside class="left-sidebar sidebar-dark" id="left-sidebar">

    <div id="sidebar" class="sidebar sidebar-with-footer">
        <!-- Aplication Brand -->
        <div class="app-brand">
            <a href="{{route('admin.dashboard')}}">
                <!-- <img src="{{Setting::get('site_logo')}}" alt="{{Setting::get('site_name')}}" class="logo"> -->
                <span class="brand-name text-uppercase">{{Setting::get('site_name')}}</span>
            </a>
        </div>
        <!-- begin sidebar scrollbar -->
        <div class="sidebar-left" data-simplebar style="height: 100%;">
            <!-- sidebar menu -->
            <ul class="nav sidebar-inner" id="sidebar-menu">

                <li class="has-sub" id="dashboard">
                    <a class="sidenav-item-link" href="{{route('admin.dashboard')}}">
                        <i class="mdi mdi-briefcase-account-outline"></i>
                        <span class="nav-text">{{tr('dashboard')}}</span>
                    </a>
                </li>

                <li class="section-title">
                    {{tr('account_management')}}
                </li>

                <li class="has-sub" id="users_crud">

                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#users" aria-expanded="false" aria-controls="users">
                        <i class="mdi mdi-account-multiple"></i>
                        <span class="nav-text">{{tr('users')}}</span> <b class="caret"></b>
                    </a>
                    <ul class="collapse" id="users" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <li id="users-create">
                                <a class="sidenav-item-link" href="{{route('admin.users.create')}}">
                                    <span class="nav-text">{{tr('add_user')}}</span>

                                </a>
                            </li>

                            <li id="users-index">
                                <a class="sidenav-item-link" href="{{route('admin.users.index')}}">
                                    <span class="nav-text">{{tr('view_users')}}</span>

                                </a>
                            </li>

                        </div>
                    </ul>
                </li>

                <li class="section-title">
                    {{tr('meetings_management')}}
                </li>

                <li class="has-sub" id="meetings">

                    <a class="sidenav-item-link" href="{{route('admin.meetings.index')}}">
                        <i class="mdi mdi-ticket"></i>
                        <span class="nav-text">{{tr('meetings')}}</span>
                    </a>
                </li>

                <li class="section-title">
                    {{tr('payment_management')}}
                </li>

                <li class="has-sub" id="subscriptions_crud">

                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#subscriptions" aria-expanded="false" aria-controls="subscriptions">
                        <i class="mdi mdi-diamond"></i>
                        <span class="nav-text">{{tr('subscriptions')}}</span> <b class="caret"></b>
                    </a>
                    <ul class="collapse" id="subscriptions" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <li id="subscriptions-create">
                                <a class="sidenav-item-link" href="{{route('admin.subscriptions.create')}}">
                                    <span class="nav-text">{{tr('add_subscription')}}</span>

                                </a>
                            </li>

                            <li id="subscriptions-view">
                                <a class="sidenav-item-link" href="{{route('admin.subscriptions.index')}}">
                                    <span class="nav-text">{{tr('view_subscriptions')}}</span>

                                </a>
                            </li>

                        </div>
                    </ul>
                </li>

                <li class="has-sub" id="subscription_payments">

                    <a class="sidenav-item-link" href="{{route('admin.subscription.payments')}}">
                        <i class="mdi mdi-ticket"></i>
                        <span class="nav-text">{{tr('subscription_payments')}}</span>
                    </a>
                    
                </li>

                <li class="section-title">
                    {{tr('setting_management')}}
                </li>
                <li class="has-sub" id="static_pages_crud">
                    <a class="sidenav-item-link" href="javascript:void(0)" data-toggle="collapse" data-target="#static_pages" aria-expanded="true" aria-controls="static_pages">
                        <i class="mdi mdi-file-multiple"></i>
                        <span class="nav-text">{{tr('static_pages')}}</span> <b class="caret"></b>
                    </a>
                    <ul class="collapse" id="static_pages" data-parent="#sidebar-menu">
                        <div class="sub-menu">

                            <li id="static_pages_create">
                                <a class="sidenav-item-link" href="{{route('admin.static_pages.create')}}">
                                    <span class="nav-text">{{tr('add_static_page')}}</span>

                                </a>
                            </li>

                            <li id="static_pages_view">
                                <a class="sidenav-item-link" href="{{route('admin.static_pages.index')}}">
                                    <span class="nav-text">{{tr('view_static_pages')}}</span>

                                </a>
                            </li>

                        </div>
                    </ul>
                </li>

                <li id="settings">
                    <a class="sidenav-item-link" href="{{route('admin.settings')}}">
                        <i class="mdi mdi-settings"></i>
                        <span class="nav-text">{{tr('settings')}}</span>
                    </a>
                </li>

                <li class="section-title">
                    {{tr('profile_management')}}
                </li>

                <li id="profile">
                    <a class="sidenav-item-link" href="{{route('admin.profile')}}">
                        <i class="mdi mdi-account"></i>
                        <span class="nav-text">{{tr('profile')}}</span>
                    </a>
                </li>

                <li>
                    <a class="sidenav-item-link" href="{{route('admin.logout')}}"   data-toggle="modal" data-target="#logoutModel">
                        <i class="mdi mdi-logout"></i>
                        <span class="nav-text">{{tr('logout')}}</span>
                    </a>
                </li>

            </ul>

        </div>

        
    </div>
</aside>


<script type="text/javascript">

	// Target id == Page 
	@if(isset($main_page)) 
        var id = "{{$main_page}}";
        $("#"+"{{$main_page}}").addClass("active expand");
        $("#"+"{{$main_page}}").find('.sidenav-item-link').click(); 
    @endif

    @if(isset($page))
        $("#{{$page}}").addClass("show");
    @endif
    
    @if(isset($sub_page)) 
        $("#{{$sub_page}}").addClass("active");
    @endif
  

   


</script>